const events = [
	{ title: 'Barrio Municipal', date: '1948' },
	{ title: 'Barrio “32 Viviendas” (Barrio Tanque)', date: '1969' },
	{ title: 'Barrio Esso', date: '1970' },
	{ title: 'Barrio Municipal Plan Alborada', date: '1975' },
	{ title: 'Barrio E.P.A.M', date: '1978' },
	{ title: 'Barrio Fibas', date: '1979' },
	{ title: 'Barrio Frigorífico', date: '1979' },
	{ title: 'Barrio Democracia', date: '1984' },
	{ title: 'Barrio San Bernardo', date: '1984' },
	{ title: 'Plan P.A.V.I', date: '1986' },
	{ title: 'Barrio Jardín', date: '1987' },
	{ title: 'Loteo Quinta Ceballos', date: '1988' },
	{ title: 'Barrio Aceitero A', date: '1988' },
	{ title: 'Barrio Aceitero B', date: '1988' },
	{ title: 'Barrio Duilio Giorgetti', date: '1988' },
	{ title: 'Plan PVP', date: '1989' },
	{ title: 'Barrio 10 Viviendas', date: '1989' },
	{ title: 'Barrio 208 Viviendas', date: '1995' },
	{ title: 'Barrio 44 Viviendas', date: '1996' },
	{ title: 'Barrio Sol Naciente', date: '1998' },
	{ title: 'Loteo Aldea Del Sol', date: '2003' },
	{ title: 'Loteo La Alameda', date: '2005' },
	{ title: 'Barrio Solos Y Solas', date: '2006' },
	{ title: 'Barrio Cáritas', date: '2006' },
	{ title: 'Barrio Plan Federal I', date: '2006' },
	{ title: 'Loteo Barrio Cáritas', date: '2009' },
	{ title: 'Loteo Quinta Ribetto', date: '2009' },
	{
		title: 'Loteo Quinta Gastaldi',
		date: '2009',
		description: '',
		img: 'assets/LineaSocial/1914 - iglesia2.jpg',
	},
];

export default events;
