const items = [
	{
		titulo: 'Lorem ipsum',
		autor: 'Gina Calcabrini',
		contenido: `La historia empieza en el año 1914, cuando el padre de familia tuvo que abandonarlos por 5 años para ir a la guerra. Vivían en Potenza Picena, Italia. La familia estaba conformada por sus padres, José y Antonia; y sus seis hijos: Luis, Eugenia, Gina, María, Humberto, y Máxima.
        
        Gina, tenía sólo tres meses de vida cuando su padre se fue. Después de cinco largos años, cuando José vuelve de la guerra, Gina todavía no lo había conocido. Lo primero que vio cuando bajó del avión, fue un desconocido con ropa rota, ya que venía de la guerra, con pelo largo y barba. Ella no podía creer que era su padre y salió corriendo cuando él la fue a abrazar. Estuvo alrededor de 15 días para reconocer y aceptar a su padre. Luego, José alquila un campo donde se van a vivir todos. El clima no acompañaba, las cosechas no tenían buenos resultados, por lo tanto, José pensaba en irse a América a recaudar fondos y así volver a Italia. 

        Antonia no estaba de acuerdo y, cuando hablaban del tema, empezaba a llorar. “Y cuando la mamá llora, lloran todos” contaba Gina. José no perdió las esperanzas y le escribió a su hermano que estaba en Argentina. El respondió que si, que en Argentina había oportunidades de trabajo. Muchos buscaron refugio en esta tierra. Lo invitó para que fuera con Luis, su hijo mayor de 12 años, ya que le iba a servir como boyero, cuidador de animales en ese entonces. Luis estaba muy entusiasmado con la propuesta, menos el resto de la familia. Para ellos, Luis era indispensable. Era el mayor de los hermanos, el encargado de ir al pueblo y hacer las compras, entre otras tareas y, además, ¡se iban a ir los dos hombres mayores de la familia! No era agradable pensar que se quedarían sin ellos. 
   Pero en ese momento, el trabajo era más importante, y así, José y Luis se fueron en busca de trabajo a la Argentina. Por otro lado, Antonia se quedó en Italia con sus 5 hijos, viviendo en el campo. A la mañana lavaba ropa de otras personas y a la noche trabajaba con el telar. Gina tiene el recuerdo de una madre fuerte y alegre, que a pesar de la situación que atravesaban, estaba contenta y siempre cantando. También era muy confiada de su marido, no creía por nada en el mundo que él haya conocido a otra mujer en Argentina. Esos rumores corrían, ya que, otras mujeres no recibían más noticias, por el simple hecho que sus maridos comenzaban otra vida allá y abandonaban la de Italia, dejando a sus mujeres e hijos solos.

   Los momentos feos en el campo, eran de noche cuando pasaban mucho miedo. Una noche de tormenta estaban todos en la cama grande con su madre, llorando y rezando. Hasta que Antonia se cansó y decidió irse a vivir al pueblo. 

   Desde que José y Luis se fueron, Antonia vivió otros 5 años más sola con sus hijos. Hasta que un día recibió una carta, donde decía que tenía que irse con ellos a Argentina. Resulta, que había rumores que comenzaba otra guerra. Al saber eso, se organizaban fiestas para despedirse de sus abuelos, donde Gina asistía dejando de lado el colegio. El director, muy enojado con Gina, fue a hablar con su madre donde le advirtió que Argentina era todo desierto, ¡que no sabía en las condiciones que iban a vivir allá! “Pobre, le decía eso en vez de darle coraje a mi mamá” acota Gina. Y así fue, cuando partieron los que faltaban para Argentina. El viaje duró 15 días, desde el 28 de enero hasta el 15 de febrero del año 1929 en un barco llamado Julio César. Eugenia tenía 17 años, Gina 14, Humberto 8, María 7 y Máxima 6. “El viaje fue muy lindo, menos una noche” relata Gina. Por las noches se armaban bailes en la parte de arriba del barco, ya que estaba lleno de personas de diferentes nacionalidades y tocaban instrumentos dependiendo su país. Había turcos, árabes, alemanes, italianos, españoles… La peor noche, fue cuando estaban cruzando el estrecho de Gibraltar y un pescado enorme rompe el ojo de buey y empezó a entrar mucha agua. Mientras tanto, el barco se movía muy fuerte y en la fiesta cuando bailaban, todos se caen. “Estábamos todas agarradas, una al lado de otra, hasta que nos caemos y estaba una vomitando por un lado, otras que lloraban por otro”. Hasta que nos avisan que vayamos abajo, porque había un problema. “Entraba mucha agua, Máxima y María gritaban porque se mojaban. Estaban todos rezando y llorando”.

   El barco Julio César, se dividía en cuatro categorías, entre ricos y pobres. Gina pertenecía a la tercera. Los de la cuarta categoría, se dividían hombres por un lado, y mujeres por otro para dormir. Contaba que una amiga napolitana estaba llena de piojos, “eran más mugrientos los napolitanos”. Así que la peluquera se encargaba de pelarlos y andaban con pañuelos en la cabeza. 
   Cuando llegaron a Argentina, Gina conoció enseguida a su padre. “Mamá, mamá, allá está” “No Gina, no es él”. 
   Una de las preguntas más frecuentes que le hicieron fue la diferencia de Argentina e Italia. Y era mucha, ya que allá estaba todo al lado y muy junto. En cambio acá, era todo “desierto”. Eso fue una gran desilusión.
   Lo mejor de Argentina, fue encontrarse con su familia, además de su hermano y su papá, tenía tíos y la familia de ellos. Lo feo, fue dejar a sus abuelos en Italia, que después de 3 años de su partida fallecieron. 

   En Argentina vivían en una Estancia de 9 dormitorios donde vivía el General. Entre familias y vecinos se ayudaban para poder sobrevivir. “Las casas eran horribles, llovía más adentro que afuera, si llovía de día no había problema, pero si era de noche, teníamos que arroyar los colchones y nos íbamos a la cocina a tomar mates”.

   La familia Calcabrini llegó en el año 1929 y, en el año 1930 hubo una crisis, debido a la escasa lluvia durante el año. Los animales se morían y la cosecha no iba bien. José alquilaba campo, donde Eugenia y Gina tenían que juntar el maíz de 40 hectáreas más o menos. “No sabíamos si reír o llorar” “Nos lastimábamos todas las piernas así que un día me avivé y le saqué un pantalón largo a mi hermano, no me importaba pasar vergüenza” “Dale Eugenia, sácate uno!” “Vos sos loca, Gina!” Y para no estar tristes de todo lo que tenían que hacer, empezaron a cantar. 

   Al final, Gina menciona que en Italia eran felices, salvo por la ausencia de su papá y hermano, pero iban al colegio y no la pasaban tan mal. Siempre que veía un pajarito mientras juntaban maíz, le comentaba a su hermana: “¡Mira Eugenia, si fuera un pajarito, cómo estaría en Italia…!” 

   Es esta una historia que evidencia el desgarro familiar, el quebranto económico, los hogares dañados. Consecuencias dolientes de los que sufrieron una guerra.`,
	},
	{
		titulo: 'Lorem ipsum',
		autor: 'Gina Calcabrini',
		contenido: `La historia empieza en el año 1914, cuando el padre de familia tuvo que abandonarlos por 5 años para ir a la guerra. Vivían en Potenza Picena, Italia. La familia estaba conformada por sus padres, José y Antonia; y sus seis hijos: Luis, Eugenia, Gina, María, Humberto, y Máxima.

        Gina, tenía sólo tres meses de vida cuando su padre se fue. Después de cinco largos años, cuando José vuelve de la guerra, Gina todavía no lo había conocido. Lo primero que vio cuando bajó del avión, fue un desconocido con ropa rota, ya que venía de la guerra, con pelo largo y barba. Ella no podía creer que era su padre y salió corriendo cuando él la fue a abrazar. Estuvo alrededor de 15 días para reconocer y aceptar a su padre. Luego, José alquila un campo donde se van a vivir todos. El clima no acompañaba, las cosechas no tenían buenos resultados, por lo tanto, José pensaba en irse a América a recaudar fondos y así volver a Italia. 

        Antonia no estaba de acuerdo y, cuando hablaban del tema, empezaba a llorar. “Y cuando la mamá llora, lloran todos” contaba Gina. José no perdió las esperanzas y le escribió a su hermano que estaba en Argentina. El respondió que si, que en Argentina había oportunidades de trabajo. Muchos buscaron refugio en esta tierra. Lo invitó para que fuera con Luis, su hijo mayor de 12 años, ya que le iba a servir como boyero, cuidador de animales en ese entonces. Luis estaba muy entusiasmado con la propuesta, menos el resto de la familia. Para ellos, Luis era indispensable. Era el mayor de los hermanos, el encargado de ir al pueblo y hacer las compras, entre otras tareas y, además, ¡se iban a ir los dos hombres mayores de la familia! No era agradable pensar que se quedarían sin ellos. 
   Pero en ese momento, el trabajo era más importante, y así, José y Luis se fueron en busca de trabajo a la Argentina. Por otro lado, Antonia se quedó en Italia con sus 5 hijos, viviendo en el campo. A la mañana lavaba ropa de otras personas y a la noche trabajaba con el telar. Gina tiene el recuerdo de una madre fuerte y alegre, que a pesar de la situación que atravesaban, estaba contenta y siempre cantando. También era muy confiada de su marido, no creía por nada en el mundo que él haya conocido a otra mujer en Argentina. Esos rumores corrían, ya que, otras mujeres no recibían más noticias, por el simple hecho que sus maridos comenzaban otra vida allá y abandonaban la de Italia, dejando a sus mujeres e hijos solos.

   Los momentos feos en el campo, eran de noche cuando pasaban mucho miedo. Una noche de tormenta estaban todos en la cama grande con su madre, llorando y rezando. Hasta que Antonia se cansó y decidió irse a vivir al pueblo. 

   Desde que José y Luis se fueron, Antonia vivió otros 5 años más sola con sus hijos. Hasta que un día recibió una carta, donde decía que tenía que irse con ellos a Argentina. Resulta, que había rumores que comenzaba otra guerra. Al saber eso, se organizaban fiestas para despedirse de sus abuelos, donde Gina asistía dejando de lado el colegio. El director, muy enojado con Gina, fue a hablar con su madre donde le advirtió que Argentina era todo desierto, ¡que no sabía en las condiciones que iban a vivir allá! “Pobre, le decía eso en vez de darle coraje a mi mamá” acota Gina. Y así fue, cuando partieron los que faltaban para Argentina. El viaje duró 15 días, desde el 28 de enero hasta el 15 de febrero del año 1929 en un barco llamado Julio César. Eugenia tenía 17 años, Gina 14, Humberto 8, María 7 y Máxima 6. “El viaje fue muy lindo, menos una noche” relata Gina. Por las noches se armaban bailes en la parte de arriba del barco, ya que estaba lleno de personas de diferentes nacionalidades y tocaban instrumentos dependiendo su país. Había turcos, árabes, alemanes, italianos, españoles… La peor noche, fue cuando estaban cruzando el estrecho de Gibraltar y un pescado enorme rompe el ojo de buey y empezó a entrar mucha agua. Mientras tanto, el barco se movía muy fuerte y en la fiesta cuando bailaban, todos se caen. “Estábamos todas agarradas, una al lado de otra, hasta que nos caemos y estaba una vomitando por un lado, otras que lloraban por otro”. Hasta que nos avisan que vayamos abajo, porque había un problema. “Entraba mucha agua, Máxima y María gritaban porque se mojaban. Estaban todos rezando y llorando”.

   El barco Julio César, se dividía en cuatro categorías, entre ricos y pobres. Gina pertenecía a la tercera. Los de la cuarta categoría, se dividían hombres por un lado, y mujeres por otro para dormir. Contaba que una amiga napolitana estaba llena de piojos, “eran más mugrientos los napolitanos”. Así que la peluquera se encargaba de pelarlos y andaban con pañuelos en la cabeza. 
   Cuando llegaron a Argentina, Gina conoció enseguida a su padre. “Mamá, mamá, allá está” “No Gina, no es él”. 
   Una de las preguntas más frecuentes que le hicieron fue la diferencia de Argentina e Italia. Y era mucha, ya que allá estaba todo al lado y muy junto. En cambio acá, era todo “desierto”. Eso fue una gran desilusión.
   Lo mejor de Argentina, fue encontrarse con su familia, además de su hermano y su papá, tenía tíos y la familia de ellos. Lo feo, fue dejar a sus abuelos en Italia, que después de 3 años de su partida fallecieron. 

   En Argentina vivían en una Estancia de 9 dormitorios donde vivía el General. Entre familias y vecinos se ayudaban para poder sobrevivir. “Las casas eran horribles, llovía más adentro que afuera, si llovía de día no había problema, pero si era de noche, teníamos que arroyar los colchones y nos íbamos a la cocina a tomar mates”.

   La familia Calcabrini llegó en el año 1929 y, en el año 1930 hubo una crisis, debido a la escasa lluvia durante el año. Los animales se morían y la cosecha no iba bien. José alquilaba campo, donde Eugenia y Gina tenían que juntar el maíz de 40 hectáreas más o menos. “No sabíamos si reír o llorar” “Nos lastimábamos todas las piernas así que un día me avivé y le saqué un pantalón largo a mi hermano, no me importaba pasar vergüenza” “Dale Eugenia, sácate uno!” “Vos sos loca, Gina!” Y para no estar tristes de todo lo que tenían que hacer, empezaron a cantar. 

   Al final, Gina menciona que en Italia eran felices, salvo por la ausencia de su papá y hermano, pero iban al colegio y no la pasaban tan mal. Siempre que veía un pajarito mientras juntaban maíz, le comentaba a su hermana: “¡Mira Eugenia, si fuera un pajarito, cómo estaría en Italia…!” 

   Es esta una historia que evidencia el desgarro familiar, el quebranto económico, los hogares dañados. Consecuencias dolientes de los que sufrieron una guerra.`,
	},
	{
		titulo: 'Lorem ipsum',
		autor: 'Gina Calcabrini',
		contenido: `La historia empieza en el año 1914, cuando el padre de familia tuvo que abandonarlos por 5 años para ir a la guerra. Vivían en Potenza Picena, Italia. La familia estaba conformada por sus padres, José y Antonia; y sus seis hijos: Luis, Eugenia, Gina, María, Humberto, y Máxima.

        Gina, tenía sólo tres meses de vida cuando su padre se fue. Después de cinco largos años, cuando José vuelve de la guerra, Gina todavía no lo había conocido. Lo primero que vio cuando bajó del avión, fue un desconocido con ropa rota, ya que venía de la guerra, con pelo largo y barba. Ella no podía creer que era su padre y salió corriendo cuando él la fue a abrazar. Estuvo alrededor de 15 días para reconocer y aceptar a su padre. Luego, José alquila un campo donde se van a vivir todos. El clima no acompañaba, las cosechas no tenían buenos resultados, por lo tanto, José pensaba en irse a América a recaudar fondos y así volver a Italia. 

        Antonia no estaba de acuerdo y, cuando hablaban del tema, empezaba a llorar. “Y cuando la mamá llora, lloran todos” contaba Gina. José no perdió las esperanzas y le escribió a su hermano que estaba en Argentina. El respondió que si, que en Argentina había oportunidades de trabajo. Muchos buscaron refugio en esta tierra. Lo invitó para que fuera con Luis, su hijo mayor de 12 años, ya que le iba a servir como boyero, cuidador de animales en ese entonces. Luis estaba muy entusiasmado con la propuesta, menos el resto de la familia. Para ellos, Luis era indispensable. Era el mayor de los hermanos, el encargado de ir al pueblo y hacer las compras, entre otras tareas y, además, ¡se iban a ir los dos hombres mayores de la familia! No era agradable pensar que se quedarían sin ellos. 
   Pero en ese momento, el trabajo era más importante, y así, José y Luis se fueron en busca de trabajo a la Argentina. Por otro lado, Antonia se quedó en Italia con sus 5 hijos, viviendo en el campo. A la mañana lavaba ropa de otras personas y a la noche trabajaba con el telar. Gina tiene el recuerdo de una madre fuerte y alegre, que a pesar de la situación que atravesaban, estaba contenta y siempre cantando. También era muy confiada de su marido, no creía por nada en el mundo que él haya conocido a otra mujer en Argentina. Esos rumores corrían, ya que, otras mujeres no recibían más noticias, por el simple hecho que sus maridos comenzaban otra vida allá y abandonaban la de Italia, dejando a sus mujeres e hijos solos.

   Los momentos feos en el campo, eran de noche cuando pasaban mucho miedo. Una noche de tormenta estaban todos en la cama grande con su madre, llorando y rezando. Hasta que Antonia se cansó y decidió irse a vivir al pueblo. 

   Desde que José y Luis se fueron, Antonia vivió otros 5 años más sola con sus hijos. Hasta que un día recibió una carta, donde decía que tenía que irse con ellos a Argentina. Resulta, que había rumores que comenzaba otra guerra. Al saber eso, se organizaban fiestas para despedirse de sus abuelos, donde Gina asistía dejando de lado el colegio. El director, muy enojado con Gina, fue a hablar con su madre donde le advirtió que Argentina era todo desierto, ¡que no sabía en las condiciones que iban a vivir allá! “Pobre, le decía eso en vez de darle coraje a mi mamá” acota Gina. Y así fue, cuando partieron los que faltaban para Argentina. El viaje duró 15 días, desde el 28 de enero hasta el 15 de febrero del año 1929 en un barco llamado Julio César. Eugenia tenía 17 años, Gina 14, Humberto 8, María 7 y Máxima 6. “El viaje fue muy lindo, menos una noche” relata Gina. Por las noches se armaban bailes en la parte de arriba del barco, ya que estaba lleno de personas de diferentes nacionalidades y tocaban instrumentos dependiendo su país. Había turcos, árabes, alemanes, italianos, españoles… La peor noche, fue cuando estaban cruzando el estrecho de Gibraltar y un pescado enorme rompe el ojo de buey y empezó a entrar mucha agua. Mientras tanto, el barco se movía muy fuerte y en la fiesta cuando bailaban, todos se caen. “Estábamos todas agarradas, una al lado de otra, hasta que nos caemos y estaba una vomitando por un lado, otras que lloraban por otro”. Hasta que nos avisan que vayamos abajo, porque había un problema. “Entraba mucha agua, Máxima y María gritaban porque se mojaban. Estaban todos rezando y llorando”.

   El barco Julio César, se dividía en cuatro categorías, entre ricos y pobres. Gina pertenecía a la tercera. Los de la cuarta categoría, se dividían hombres por un lado, y mujeres por otro para dormir. Contaba que una amiga napolitana estaba llena de piojos, “eran más mugrientos los napolitanos”. Así que la peluquera se encargaba de pelarlos y andaban con pañuelos en la cabeza. 
   Cuando llegaron a Argentina, Gina conoció enseguida a su padre. “Mamá, mamá, allá está” “No Gina, no es él”. 
   Una de las preguntas más frecuentes que le hicieron fue la diferencia de Argentina e Italia. Y era mucha, ya que allá estaba todo al lado y muy junto. En cambio acá, era todo “desierto”. Eso fue una gran desilusión.
   Lo mejor de Argentina, fue encontrarse con su familia, además de su hermano y su papá, tenía tíos y la familia de ellos. Lo feo, fue dejar a sus abuelos en Italia, que después de 3 años de su partida fallecieron. 

   En Argentina vivían en una Estancia de 9 dormitorios donde vivía el General. Entre familias y vecinos se ayudaban para poder sobrevivir. “Las casas eran horribles, llovía más adentro que afuera, si llovía de día no había problema, pero si era de noche, teníamos que arroyar los colchones y nos íbamos a la cocina a tomar mates”.

   La familia Calcabrini llegó en el año 1929 y, en el año 1930 hubo una crisis, debido a la escasa lluvia durante el año. Los animales se morían y la cosecha no iba bien. José alquilaba campo, donde Eugenia y Gina tenían que juntar el maíz de 40 hectáreas más o menos. “No sabíamos si reír o llorar” “Nos lastimábamos todas las piernas así que un día me avivé y le saqué un pantalón largo a mi hermano, no me importaba pasar vergüenza” “Dale Eugenia, sácate uno!” “Vos sos loca, Gina!” Y para no estar tristes de todo lo que tenían que hacer, empezaron a cantar. 

   Al final, Gina menciona que en Italia eran felices, salvo por la ausencia de su papá y hermano, pero iban al colegio y no la pasaban tan mal. Siempre que veía un pajarito mientras juntaban maíz, le comentaba a su hermana: “¡Mira Eugenia, si fuera un pajarito, cómo estaría en Italia…!” 

   Es esta una historia que evidencia el desgarro familiar, el quebranto económico, los hogares dañados. Consecuencias dolientes de los que sufrieron una guerra.`,
	},
	{
		titulo: 'Lorem ipsum',
		autor: 'Gina Calcabrini',
		contenido: `La historia empieza en el año 1914, cuando el padre de familia tuvo que abandonarlos por 5 años para ir a la guerra. Vivían en Potenza Picena, Italia. La familia estaba conformada por sus padres, José y Antonia; y sus seis hijos: Luis, Eugenia, Gina, María, Humberto, y Máxima.

        Gina, tenía sólo tres meses de vida cuando su padre se fue. Después de cinco largos años, cuando José vuelve de la guerra, Gina todavía no lo había conocido. Lo primero que vio cuando bajó del avión, fue un desconocido con ropa rota, ya que venía de la guerra, con pelo largo y barba. Ella no podía creer que era su padre y salió corriendo cuando él la fue a abrazar. Estuvo alrededor de 15 días para reconocer y aceptar a su padre. Luego, José alquila un campo donde se van a vivir todos. El clima no acompañaba, las cosechas no tenían buenos resultados, por lo tanto, José pensaba en irse a América a recaudar fondos y así volver a Italia. 

        Antonia no estaba de acuerdo y, cuando hablaban del tema, empezaba a llorar. “Y cuando la mamá llora, lloran todos” contaba Gina. José no perdió las esperanzas y le escribió a su hermano que estaba en Argentina. El respondió que si, que en Argentina había oportunidades de trabajo. Muchos buscaron refugio en esta tierra. Lo invitó para que fuera con Luis, su hijo mayor de 12 años, ya que le iba a servir como boyero, cuidador de animales en ese entonces. Luis estaba muy entusiasmado con la propuesta, menos el resto de la familia. Para ellos, Luis era indispensable. Era el mayor de los hermanos, el encargado de ir al pueblo y hacer las compras, entre otras tareas y, además, ¡se iban a ir los dos hombres mayores de la familia! No era agradable pensar que se quedarían sin ellos. 
   Pero en ese momento, el trabajo era más importante, y así, José y Luis se fueron en busca de trabajo a la Argentina. Por otro lado, Antonia se quedó en Italia con sus 5 hijos, viviendo en el campo. A la mañana lavaba ropa de otras personas y a la noche trabajaba con el telar. Gina tiene el recuerdo de una madre fuerte y alegre, que a pesar de la situación que atravesaban, estaba contenta y siempre cantando. También era muy confiada de su marido, no creía por nada en el mundo que él haya conocido a otra mujer en Argentina. Esos rumores corrían, ya que, otras mujeres no recibían más noticias, por el simple hecho que sus maridos comenzaban otra vida allá y abandonaban la de Italia, dejando a sus mujeres e hijos solos.

   Los momentos feos en el campo, eran de noche cuando pasaban mucho miedo. Una noche de tormenta estaban todos en la cama grande con su madre, llorando y rezando. Hasta que Antonia se cansó y decidió irse a vivir al pueblo. 

   Desde que José y Luis se fueron, Antonia vivió otros 5 años más sola con sus hijos. Hasta que un día recibió una carta, donde decía que tenía que irse con ellos a Argentina. Resulta, que había rumores que comenzaba otra guerra. Al saber eso, se organizaban fiestas para despedirse de sus abuelos, donde Gina asistía dejando de lado el colegio. El director, muy enojado con Gina, fue a hablar con su madre donde le advirtió que Argentina era todo desierto, ¡que no sabía en las condiciones que iban a vivir allá! “Pobre, le decía eso en vez de darle coraje a mi mamá” acota Gina. Y así fue, cuando partieron los que faltaban para Argentina. El viaje duró 15 días, desde el 28 de enero hasta el 15 de febrero del año 1929 en un barco llamado Julio César. Eugenia tenía 17 años, Gina 14, Humberto 8, María 7 y Máxima 6. “El viaje fue muy lindo, menos una noche” relata Gina. Por las noches se armaban bailes en la parte de arriba del barco, ya que estaba lleno de personas de diferentes nacionalidades y tocaban instrumentos dependiendo su país. Había turcos, árabes, alemanes, italianos, españoles… La peor noche, fue cuando estaban cruzando el estrecho de Gibraltar y un pescado enorme rompe el ojo de buey y empezó a entrar mucha agua. Mientras tanto, el barco se movía muy fuerte y en la fiesta cuando bailaban, todos se caen. “Estábamos todas agarradas, una al lado de otra, hasta que nos caemos y estaba una vomitando por un lado, otras que lloraban por otro”. Hasta que nos avisan que vayamos abajo, porque había un problema. “Entraba mucha agua, Máxima y María gritaban porque se mojaban. Estaban todos rezando y llorando”.

   El barco Julio César, se dividía en cuatro categorías, entre ricos y pobres. Gina pertenecía a la tercera. Los de la cuarta categoría, se dividían hombres por un lado, y mujeres por otro para dormir. Contaba que una amiga napolitana estaba llena de piojos, “eran más mugrientos los napolitanos”. Así que la peluquera se encargaba de pelarlos y andaban con pañuelos en la cabeza. 
   Cuando llegaron a Argentina, Gina conoció enseguida a su padre. “Mamá, mamá, allá está” “No Gina, no es él”. 
   Una de las preguntas más frecuentes que le hicieron fue la diferencia de Argentina e Italia. Y era mucha, ya que allá estaba todo al lado y muy junto. En cambio acá, era todo “desierto”. Eso fue una gran desilusión.
   Lo mejor de Argentina, fue encontrarse con su familia, además de su hermano y su papá, tenía tíos y la familia de ellos. Lo feo, fue dejar a sus abuelos en Italia, que después de 3 años de su partida fallecieron. 

   En Argentina vivían en una Estancia de 9 dormitorios donde vivía el General. Entre familias y vecinos se ayudaban para poder sobrevivir. “Las casas eran horribles, llovía más adentro que afuera, si llovía de día no había problema, pero si era de noche, teníamos que arroyar los colchones y nos íbamos a la cocina a tomar mates”.

   La familia Calcabrini llegó en el año 1929 y, en el año 1930 hubo una crisis, debido a la escasa lluvia durante el año. Los animales se morían y la cosecha no iba bien. José alquilaba campo, donde Eugenia y Gina tenían que juntar el maíz de 40 hectáreas más o menos. “No sabíamos si reír o llorar” “Nos lastimábamos todas las piernas así que un día me avivé y le saqué un pantalón largo a mi hermano, no me importaba pasar vergüenza” “Dale Eugenia, sácate uno!” “Vos sos loca, Gina!” Y para no estar tristes de todo lo que tenían que hacer, empezaron a cantar. 

   Al final, Gina menciona que en Italia eran felices, salvo por la ausencia de su papá y hermano, pero iban al colegio y no la pasaban tan mal. Siempre que veía un pajarito mientras juntaban maíz, le comentaba a su hermana: “¡Mira Eugenia, si fuera un pajarito, cómo estaría en Italia…!” 

   Es esta una historia que evidencia el desgarro familiar, el quebranto económico, los hogares dañados. Consecuencias dolientes de los que sufrieron una guerra.`,
	},
	{
		titulo: 'Lorem ipsum',
		autor: 'Gina Calcabrini',
		contenido: `La historia empieza en el año 1914, cuando el padre de familia tuvo que abandonarlos por 5 años para ir a la guerra. Vivían en Potenza Picena, Italia. La familia estaba conformada por sus padres, José y Antonia; y sus seis hijos: Luis, Eugenia, Gina, María, Humberto, y Máxima.

        Gina, tenía sólo tres meses de vida cuando su padre se fue. Después de cinco largos años, cuando José vuelve de la guerra, Gina todavía no lo había conocido. Lo primero que vio cuando bajó del avión, fue un desconocido con ropa rota, ya que venía de la guerra, con pelo largo y barba. Ella no podía creer que era su padre y salió corriendo cuando él la fue a abrazar. Estuvo alrededor de 15 días para reconocer y aceptar a su padre. Luego, José alquila un campo donde se van a vivir todos. El clima no acompañaba, las cosechas no tenían buenos resultados, por lo tanto, José pensaba en irse a América a recaudar fondos y así volver a Italia. 

        Antonia no estaba de acuerdo y, cuando hablaban del tema, empezaba a llorar. “Y cuando la mamá llora, lloran todos” contaba Gina. José no perdió las esperanzas y le escribió a su hermano que estaba en Argentina. El respondió que si, que en Argentina había oportunidades de trabajo. Muchos buscaron refugio en esta tierra. Lo invitó para que fuera con Luis, su hijo mayor de 12 años, ya que le iba a servir como boyero, cuidador de animales en ese entonces. Luis estaba muy entusiasmado con la propuesta, menos el resto de la familia. Para ellos, Luis era indispensable. Era el mayor de los hermanos, el encargado de ir al pueblo y hacer las compras, entre otras tareas y, además, ¡se iban a ir los dos hombres mayores de la familia! No era agradable pensar que se quedarían sin ellos. 
   Pero en ese momento, el trabajo era más importante, y así, José y Luis se fueron en busca de trabajo a la Argentina. Por otro lado, Antonia se quedó en Italia con sus 5 hijos, viviendo en el campo. A la mañana lavaba ropa de otras personas y a la noche trabajaba con el telar. Gina tiene el recuerdo de una madre fuerte y alegre, que a pesar de la situación que atravesaban, estaba contenta y siempre cantando. También era muy confiada de su marido, no creía por nada en el mundo que él haya conocido a otra mujer en Argentina. Esos rumores corrían, ya que, otras mujeres no recibían más noticias, por el simple hecho que sus maridos comenzaban otra vida allá y abandonaban la de Italia, dejando a sus mujeres e hijos solos.

   Los momentos feos en el campo, eran de noche cuando pasaban mucho miedo. Una noche de tormenta estaban todos en la cama grande con su madre, llorando y rezando. Hasta que Antonia se cansó y decidió irse a vivir al pueblo. 

   Desde que José y Luis se fueron, Antonia vivió otros 5 años más sola con sus hijos. Hasta que un día recibió una carta, donde decía que tenía que irse con ellos a Argentina. Resulta, que había rumores que comenzaba otra guerra. Al saber eso, se organizaban fiestas para despedirse de sus abuelos, donde Gina asistía dejando de lado el colegio. El director, muy enojado con Gina, fue a hablar con su madre donde le advirtió que Argentina era todo desierto, ¡que no sabía en las condiciones que iban a vivir allá! “Pobre, le decía eso en vez de darle coraje a mi mamá” acota Gina. Y así fue, cuando partieron los que faltaban para Argentina. El viaje duró 15 días, desde el 28 de enero hasta el 15 de febrero del año 1929 en un barco llamado Julio César. Eugenia tenía 17 años, Gina 14, Humberto 8, María 7 y Máxima 6. “El viaje fue muy lindo, menos una noche” relata Gina. Por las noches se armaban bailes en la parte de arriba del barco, ya que estaba lleno de personas de diferentes nacionalidades y tocaban instrumentos dependiendo su país. Había turcos, árabes, alemanes, italianos, españoles… La peor noche, fue cuando estaban cruzando el estrecho de Gibraltar y un pescado enorme rompe el ojo de buey y empezó a entrar mucha agua. Mientras tanto, el barco se movía muy fuerte y en la fiesta cuando bailaban, todos se caen. “Estábamos todas agarradas, una al lado de otra, hasta que nos caemos y estaba una vomitando por un lado, otras que lloraban por otro”. Hasta que nos avisan que vayamos abajo, porque había un problema. “Entraba mucha agua, Máxima y María gritaban porque se mojaban. Estaban todos rezando y llorando”.

   El barco Julio César, se dividía en cuatro categorías, entre ricos y pobres. Gina pertenecía a la tercera. Los de la cuarta categoría, se dividían hombres por un lado, y mujeres por otro para dormir. Contaba que una amiga napolitana estaba llena de piojos, “eran más mugrientos los napolitanos”. Así que la peluquera se encargaba de pelarlos y andaban con pañuelos en la cabeza. 
   Cuando llegaron a Argentina, Gina conoció enseguida a su padre. “Mamá, mamá, allá está” “No Gina, no es él”. 
   Una de las preguntas más frecuentes que le hicieron fue la diferencia de Argentina e Italia. Y era mucha, ya que allá estaba todo al lado y muy junto. En cambio acá, era todo “desierto”. Eso fue una gran desilusión.
   Lo mejor de Argentina, fue encontrarse con su familia, además de su hermano y su papá, tenía tíos y la familia de ellos. Lo feo, fue dejar a sus abuelos en Italia, que después de 3 años de su partida fallecieron. 

   En Argentina vivían en una Estancia de 9 dormitorios donde vivía el General. Entre familias y vecinos se ayudaban para poder sobrevivir. “Las casas eran horribles, llovía más adentro que afuera, si llovía de día no había problema, pero si era de noche, teníamos que arroyar los colchones y nos íbamos a la cocina a tomar mates”.

   La familia Calcabrini llegó en el año 1929 y, en el año 1930 hubo una crisis, debido a la escasa lluvia durante el año. Los animales se morían y la cosecha no iba bien. José alquilaba campo, donde Eugenia y Gina tenían que juntar el maíz de 40 hectáreas más o menos. “No sabíamos si reír o llorar” “Nos lastimábamos todas las piernas así que un día me avivé y le saqué un pantalón largo a mi hermano, no me importaba pasar vergüenza” “Dale Eugenia, sácate uno!” “Vos sos loca, Gina!” Y para no estar tristes de todo lo que tenían que hacer, empezaron a cantar. 

   Al final, Gina menciona que en Italia eran felices, salvo por la ausencia de su papá y hermano, pero iban al colegio y no la pasaban tan mal. Siempre que veía un pajarito mientras juntaban maíz, le comentaba a su hermana: “¡Mira Eugenia, si fuera un pajarito, cómo estaría en Italia…!” 

   Es esta una historia que evidencia el desgarro familiar, el quebranto económico, los hogares dañados. Consecuencias dolientes de los que sufrieron una guerra.`,
	},
];

export default items;
