const items = [
	{ img: '/assets/Exhibiciones/01/01.jpg' },
	{ img: '/assets/Exhibiciones/01/02.jpg' },
	{ img: '/assets/Exhibiciones/01/03.jpg' },
	{ img: '/assets/Exhibiciones/01/04.jpg' },
	{ img: '/assets/Exhibiciones/01/05.jpg' },
	{ img: '/assets/Exhibiciones/01/06.jpg' },
	{ img: '/assets/Exhibiciones/01/07.jpg' },
	{ img: '/assets/Exhibiciones/01/08.jpg' },
	{ img: '/assets/Exhibiciones/01/09.jpg' },
	{ img: '/assets/Exhibiciones/01/10.jpg' },
	{ img: '/assets/Exhibiciones/01/11.jpg' },
	{ img: '/assets/Exhibiciones/01/12.jpg' },
	{ img: '/assets/Exhibiciones/01/13.jpg' },
	{ img: '/assets/Exhibiciones/01/14.jpg' },
	{ img: '/assets/Exhibiciones/01/15.jpg' },
	{ img: '/assets/Exhibiciones/01/16.jpg' },
	{ img: '/assets/Exhibiciones/01/17.jpg' },
	{ img: '/assets/Exhibiciones/01/18.jpg' },
	{ img: '/assets/Exhibiciones/01/19.jpg' },
	{ img: '/assets/Exhibiciones/01/20.jpg' },
	{ img: '/assets/Exhibiciones/01/21.jpg' },
	{ img: '/assets/Exhibiciones/01/22.jpg' },
	{ img: '/assets/Exhibiciones/01/23.jpg' },
	{ img: '/assets/Exhibiciones/01/24.jpg' },
	{ img: '/assets/Exhibiciones/01/25.jpg' },
];

export default items;
